def set_options(opt) :
	pass

def configure(conf) :
	pass

def build(bld) :
	inst_dir = '${PREFIX}/lib/python/pypeline'
	bld.install_files(inst_dir,'__init__.py')
	bld.install_files(inst_dir,'pypeline.py')
